language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - vendor/bin/phpcs DotBlue/Sniffs --standard=DotBlue/ruleset.xml -p -s

script: vendor/bin/tester DotBlue/tests
