language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - mkdir ../DotBlue
  - cp * ../DotBlue -R
  - cd ../DotBlue
  - vendor/bin/phpcs Sniffs --standard=./ruleset.xml -p -s

script: vendor/bin/tester tests
