<?php

use DotBlue\CodeSniffer\Helpers\Tester;


require __DIR__ . '/bootstrap.php';

function formatNoSpaceBeforeMessage($operand)
{
	return 'There must be one space before "' . $operand . '". No space found.';
}

function formatNoSpaceAfterMessage($operand)
{
	return 'There must be one space after "' . $operand . '". No space found.';
}

function formatMoreSpaceBeforeMessage($operand)
{
	return 'There must be one space before "' . $operand . '". 2 spaces found.';
}

function formatMoreSpaceAfterMessage($operand)
{
	return 'There must be one space after "' . $operand . '". 2 spaces found.';
}

$tester = new Tester();
$tester->setFile('OperatorsSpacing.NoSpace')
	->setSniff('WhiteSpace.OperatorsSpacing')
		->expectMessage(formatNoSpaceBeforeMessage('='))
			->onLine(3)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('='))
			->onLine(3)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('+='))
			->onLine(4)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('+='))
			->onLine(4)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('-='))
			->onLine(5)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('-='))
			->onLine(5)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('/='))
			->onLine(6)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('/='))
			->onLine(6)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('*='))
			->onLine(7)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('*='))
			->onLine(7)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('%='))
			->onLine(8)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('%='))
			->onLine(8)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('+'))
			->onLine(9)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('+'))
			->onLine(9)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('-'))
			->onLine(10)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('-'))
			->onLine(10)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('/'))
			->onLine(11)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('/'))
			->onLine(11)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('*'))
			->onLine(12)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('*'))
			->onLine(12)
	->getFile()
		->expectMessage(formatNoSpaceBeforeMessage('%'))
			->onLine(13)
	->getFile()
		->expectMessage(formatNoSpaceAfterMessage('%'))
			->onLine(13)
	->isFixable();

$tester->setFile('OperatorsSpacing.MoreSpace')
	->setSniff('WhiteSpace.OperatorsSpacing')
		->expectMessage(formatMoreSpaceBeforeMessage('='))
			->onLine(3)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('='))
			->onLine(3)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('+='))
			->onLine(4)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('+='))
			->onLine(4)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('-='))
			->onLine(5)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('-='))
			->onLine(5)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('/='))
			->onLine(6)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('/='))
			->onLine(6)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('*='))
			->onLine(7)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('*='))
			->onLine(7)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('%='))
			->onLine(8)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('%='))
			->onLine(8)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('+'))
			->onLine(9)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('+'))
			->onLine(9)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('-'))
			->onLine(10)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('-'))
			->onLine(10)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('/'))
			->onLine(11)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('/'))
			->onLine(11)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('*'))
			->onLine(12)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('*'))
			->onLine(12)
	->getFile()
		->expectMessage(formatMoreSpaceBeforeMessage('%'))
			->onLine(13)
	->getFile()
		->expectMessage(formatMoreSpaceAfterMessage('%'))
			->onLine(13)
	->isFixable();


$tester->test();
